### ISSUE TITLE
Build Error due to unknown versions of `ring` and `untrusted`

### ISSUE THREAD

**Issue by KuabeM** [drahnr/scalpel#14]
`ring` and `untrusted` have yanked a lot of versions such that those we use are no longer available. Trying to build results in 
```
$ cargo b
    Updating crates.io index
error: failed to select a version for the requirement `ring = "^0.12.1"`
  candidate versions found which didn't match: 0.14.3, 0.14.2, 0.14.1, ...
  location searched: crates.io index
required by package `scalpel-bin v0.3.0-alpha.1 (/home/korbinian/Nello/tools/scalpel)`
```

Simple solution probably is to bump versions to `ring = "0.13"` and `untrusted = "0.6"`. Tests are running locally. I'll open a PR for that.

**Comment by drahnr** [comment]
If we would have checked in the cargo lock it would be just fine, but I forgot :)

But at some point we need to update anyways, so 👍
