### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by drahnr** [drahnr/scalpel#7]
Use two structs (maybe a generic with two marker structs, I can't seem to find the rust page which descsribes that pattern :( ) and implement `From` for each other. Depending on the input use one or the other to parse the type and maybe use one as the internal representation or a third as the internal representation.
Each of those structs than should impl a set of traits, `FromFile` `ToFile` `ToCHeader`? The use generics with constraints on the type :) makes the code easier to read + gives maintainability for free

**Comment by KuabeM** [comment]
I wanted to get started with this now. My understanding of this:

- use one struct to parse binary input, one for hex input which hold the content in `BytesMut`
- implement `FromFile` and `ToFile` traits for both, but I can't find information on those.. do you have any resources on that?
- implement `cut`, `replace`, `concat` etc. for both structs

did I get it right?

**Comment by KuabeM** [comment]
Have a look at #13, I started something there.

**Comment by drahnr** [comment]
2.0.0 :tada:
