### ISSUE TITLE
cut_out_bytes looks fishy

### ISSUE THREAD

**Issue by drahnr** [drahnr/scalpel#9]
it seems content is always the same and as such a multi frame cut out should end up being wrong, see #8

The loop imho does not make much sense or I do not understand `.to_vec()` of `BytesMut` properly.

Possible solutions: Better test cases, move the `fn cut_out_bytes` to `Bytes` as input and `BytesMut` as output, as such one can verify things are correct programmatically within test cases.

**Comment by KuabeM** [comment]
The loop dates back to the very beginning, I agree that this implementation is no good. I'd rather go for a similar approach as in the `replace` module to operate on `BytesMut` as you suggested. The current implementation was just the easy way of get it to work with hex files.

**Comment by drahnr** [comment]
I guess this is fixed as of 2.0.0?
